apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clear-sessions
spec:
  schedule: "0 0 1 * *"
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 90
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 30
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: django-clear-sessions
              image: django_app:latest
              ports:
                - containerPort: 80
              imagePullPolicy: Never
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - configMapRef:
                    name: django-app-config
          restartPolicy: Never
